name: Sync main to dev branches

on:
  push:
    branches:
      - main  # Trigger only when main is updated

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Important: get full history for merging

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into all dev branches
        run: |
          for branch in $(git branch -r | grep 'origin/dev'); do
            dev_branch=${branch#origin/}
            echo "Merging main into $dev_branch..."
            git checkout $dev_branch
            git merge origin/main --no-edit || true
            git push origin $dev_branch
          done
